### ISSUE TITLE
How to use STAThread in winform application ?

### ISSUE THREAD

**Issue by Charltsing** [aelyo-softworks/Wice#3]
https://learn.microsoft.com/en-us/dotnet/api/system.stathreadattribute
Windows Forms apps must be single-threaded if they communicate with Windows system components such as the Clipboard or Windows common dialog boxes, or if they use system features such as drag-and-drop functionality. 

I try Wice in my winform application, but Main() must be [MTAThread], if i try [STAThread], it report Win32Exception(0x80004005）, in DirectN.TextServicesFunctions.Shutdown(ITextServicesservices), when windows is closed.

Maybe it is probably because DirectN is an MTAThread ??

Do you know, How to use STAThread in winform + Wice application ?

**Comment by smourier** [comment]
Wice doesn't mandate to be started in MTA nor STA.

What scenario are you trying the involes Wice & Winforms? This is clearly not something that's been tested as Wice can run for itself independently from any other UI framework.

If you can share some reproducing code, I can have a look at it.

**Comment by Charltsing** [comment]
[STAThread]
static void Main()

![1](https://github.com/aelyo-softworks/Wice/assets/19963715/e265f942-2bf4-44c1-8cbd-b19b873bc2d2)

close application, it report
![2](https://github.com/aelyo-softworks/Wice/assets/19963715/0caa45a4-7b21-4c11-a161-c64d7270535a)

**Comment by smourier** [comment]
Ok, this is because Wice's RichTextBox visual internally uses Windows' `Richedit` component (text services https://learn.microsoft.com/en-us/windows/win32/api/tom/) and this component is (probably) STA-based which means it must be disposed on the same thread on which it was created. When it's not it causes this error.

So, it's more a bug of the Wice Gallery that wasn't disposing this component at the right time. I've just fixed https://github.com/aelyo-softworks/Wice/commit/ea549b601221200695a2ce70b5596c118aadcbf6

**Comment by Charltsing** [comment]
i try lastest Wice.Samples.Gallery, it still report same error
[error.zip](https://github.com/aelyo-softworks/Wice/files/13173204/error.zip)
